[project]
name = "vpc-delete"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.20"
dependencies = [
    "boto3==1.7.50",
    "botocore==1.10.50",
]
